name: seed
description: "Seed is a foundational package designed to provide reusable building blocks for API Dash projects."
version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  test: ^1.28.0
